name: Deploy Fullstack App to Azure

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: nmiproduksie
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend: build React app
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build React frontend
        working-directory: frontend
        run: CI=false npm run build

      # Backend: set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      # Copy frontend build into backend for serving
      - name: Move React build into backend
        run: |
          rm -rf backend/frontend
          mkdir -p backend/frontend
          cp -r frontend/build/* backend/frontend/

      # Deploy using Azure Web App Deploy Action
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend
